name: GHCR - Install SD-Core 5G

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'The server IP address'
        required: true
        default: '10.176.27.143'
      branch_name:
        description: 'The branch name to use'
        required: true
        default: 'main'

jobs:
  install:
    runs-on: [self-hosted]  # Using our own self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Variables
        run: |
          echo "ROOT_DIR=$(pwd)" >> $GITHUB_ENV
          echo "AETHER_ROOT_DIR=$(pwd)" >> $GITHUB_ENV
          echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV

      - name: Set Locale to UTF-8
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

      - name: Cache APT Packages
        uses: actions/cache@v2
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install Docker and Dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y \
            containerd.io docker-ce docker-ce-cli \
            git curl make net-tools pipx python3-venv sshpass netplan.io \
            iptables jq sed
          pipx install --include-deps ansible || true  # Ignore if already installed
          pipx ensurepath

      - name: Start Docker service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo systemctl status docker

      - name: Debug PATH and Installed Tools
        run: |
          echo "Current PATH: $PATH"
          which sed || echo "sed not found"
          ls -l /usr/bin/sed || echo "/usr/bin/sed not found"

      - name: Set up Docker authentication for GHCR
        run: |
          if command -v docker &> /dev/null; then
            sudo docker login ghcr.io -u "${{ secrets.GHCRUSER }}" --password-stdin <<< "${{ secrets.GHCRPASS }}"
          else
            echo "Docker is not installed or not found. Exiting."
            exit 1
          fi

      - name: Install Kubernetes and SD-Core
        run: |
          make aether-k8s-install aether-5gc-install
          kubectl get pods -n omec
